version: '2'
services:
  my_app:
    image: charliefeng/parser:1.0
    build: .
    ports:
      - "5000:5000"
    links:
      - my_postgres

  my_postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

