version: '2'
services:
  my_app:
    image: charliefeng/parser:1.5
    build: .
    ports:
      - "5000:5000"
    links:
      - my_postgres
    depends_on:
      - my_redis

  my_postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  my_redis:
    image: redis
    ports:
      - "6379:6379"